#!/bin/sh

results="$1"
shift

already_done () {
    pkg="$1"
    version="$2"
    arch=$(dpkg-architecture -qDEB_BUILD_ARCH)
    base="${pkg}_${version}_${arch}"
    buildinfo="${base}.buildinfo"

    printf 'Checking binary artifacts for %s\n' "$pkg"
    state=find-pkgs
    while IFS= read -r line; do
        case "$state" in
        find-pkgs)
            test "$line" = "Checksums-Sha1:" || continue
            state=process
            ;;
        process)
            case "$line" in
            " "*) : ;;
            *) break ;;
            esac
            _pkg=$(printf '%s' "$line" | awk '{print $3}')
            file="$results"/"$_pkg"
            printf '  - Checking for %s\n' "$file"
            test -f "$file" || return 1
        esac
    done < "$buildinfo"

    printf 'Binary artifacts for %s version %s already exists.\n' \
           "$pkg" "$version"
    return 0
}

for pkg in "$@"; do
    version=$(dpkg-parsechangelog -l "$pkg"/debian/changelog \
              | sed -ne "s/^Version: \(.*\)/\1/p")
    already_done "$pkg" "$version" && continue
    sudo bash ./tools/pbuilder build "$pkg"
done
