#!/bin/sh

already_done () {
    pkg="$1"
    version="$2"
    base="${pkg}_${version}_source"
    buildinfo="${base}.buildinfo"

    printf 'Checking source artifacts for %s\n' "$pkg"
    test -f "$buildinfo" || return 1
    state=find-pkgs
    while IFS= read -r line; do
        case "$state" in
        find-pkgs)
            test "$line" = "Checksums-Sha1:" || continue
            state=process
            ;;
        process)
            case "$line" in
            " "*) : ;;
            *) break ;;
            esac
            file=$(printf '%s' "$line" | awk '{print $3}')
            printf '  - Checking for %s\n' "$file"
            test -f "$file" || return 1
        esac
    done < "$buildinfo"

    printf 'Source artifacts for %s version %s already exists.\n' \
           "$pkg" "$version"
    return 0
}

for pkg in "$@"; do
    version=$(dpkg-parsechangelog -l "$pkg"/debian/changelog \
              | sed -ne "s/^Version: \(.*\)/\1/p")
    already_done "$pkg" "$version" && continue
    (cd "$pkg" && dpkg-buildpackage -S -d;)
done
