#!/bin/bash

euid=$(id -u)

. ./pbuilder.conf || exit 1

build_results () {
    test -d "${BUILDRESULT}" || sudo mkdir -p "${BUILDRESULT}"
    sudo chown "${BUILDRESULTUID}:${BUILDRESULTGID}" "${BUILDRESULT}"
}

build_packages () {
    test -f "${BUILDRESULT}/Packages" || sudo touch "${BUILDRESULT}/Packages"
}

cmd="$1"
shift

case "$cmd" in
update)
    build_packages
    ;;
build)
    pkg="$1"
    shift
    version=$(dpkg-parsechangelog -l "$pkg"/debian/changelog \
              | sed -ne "s/^Version: \(.*\)/\1/p")
    dsc="${pkg}_${version}.dsc"
    set -- "$dsc"
    ;;
esac

if test "$euid" = 0; then
    pbuilder "$cmd" --configfile ./pbuilder.conf "$@"
    rc=$?
else
    sudo -E -u root pbuilder "$cmd" --configfile ./pbuilder.conf "$@"
    rc=$?
fi

case "$cmd" in
create|update)
    build_results
    build_packages
    ;;
esac

exit "$rc"
